### ISSUE TITLE
Issue with Saving Registered Accounts to Result Files

### ISSUE THREAD

**Issue by capuccino96** [gui-fkb/twitch-accounts#3]
I wanted to let you know that the accounts registered by the program are not being copied to the result .txt files. Could you please check this issue? It seems like there's a problem with the data being saved or copied into the files.
![Captura de pantalla 2024-08-05 004820](https://github.com/user-attachments/assets/f9dafdb3-ec6c-4fc2-86ea-c09afff10dd2)

**Comment by vrstrabo** [comment]
do you have tg? I can help you with that I can check the code and fix it

**Comment by gui-fkb** [comment]
This issue should be resolved by [354fe339e2bcad6cfea13fa11a56c132169386d7](https://github.com/gui-fkb/twitch-accounts/commit/354fe339e2bcad6cfea13fa11a56c132169386d7).
