### ISSUE TITLE
Is it possible to somehow remove email confirmation? 

### ISSUE THREAD

**Issue by Andro1515** [gui-fkb/twitch-accounts#7]
Is it possible to somehow remove email confirmation?

A Twitch account was created but I can't log in, it asks for an email code but I can't log in to the email, there is no password
Is it possible to create a Twitch account without confirming the email on Twitch?

I also wanted to ask if it is possible to change the creation of random logins and passwords from Twitch, since their data format is long

**Comment by gui-fkb** [comment]
Currently, e-mail confirmation is a must for TwitchTV account creations, Unfortunately, you cannot bypass this step, as Twitch requires email or phone verification for account activation. I don't know if you have tried to run the bot already, but it creates an account and confirm the e-mail automatically through a e-mail generator service.

And yeah, you can modify the code responsible for generating random logins and passwords to suit your preferences. You can customize the format to make it simpler or more specific to your needs.
